### Updating the MySQL root password ###
# Runs on first container start to ensure password uniqueness across all containers
# The password is stored inside the file /etc/ansible/mysql_password

- name: MySQL | Check if a random password has already been generated
  stat: path=/etc/ansible/mysql_password
  register: random_password_generated

- name: MySQL | Use already generated password
  set_fact:
    mysql_root_current_password: "{{ lookup('password', '/etc/ansible/mysql_password length=12') }}"
  when: random_password_generated.stat.exists == True

- name: MySQL | Keep current password reference
  set_fact:
    mysql_root_current_password: "{{ mysql_root_password }}"
  when: random_password_generated.stat.exists == False

- name: MySQL | Generate or reuse random root password
  set_fact:
    mysql_root_password: "{{ lookup('password', '/etc/ansible/mysql_password length=12') }}"
  tags:
    - skip-install

- name: MySQL | Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_current_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ server_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL | Remove file /root/.my.cnf
  file:
   path: /root/.my.cnf
   state: absent

- name: MySQL | Configuration file /root/.my.cnf
  template:
    src: root-my-cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: MySQL | Remove the MySQL test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent
